### PR TITLE
update moment.js version and create nodejs example

### PR DESCRIPTION
**Pull request by justbill2020**
- updated moment.js version in vendor folder
- added r.js (require.js)
- created nodejs example

Minor version bump, Security fix

- corrects security advisories 55 & 532

https://github.com/moment/moment/issues/4163
https://github.com/moment/moment/pull/4326

Update package.json and readme.

### CODE REVIEW

**Comment by justbill2020** [comment]
@SeverinDK I thought you might want to review before merging. Also, I thought we might want to change the "master" branch to "main" as per the new standard on github. 

Let me know your thoughts on both. 

I will merge after I hear back from you and will rename the branch after you give the ok. I don't want to come in and fully take over.

**Comment by SeverinDK** [comment]
Nice one @justbill2020 - I will go over this tomorrow and get it merged in. Thank you for the contribution!

**Comment by SeverinDK** [comment]
@justbill2020 Looks good. You can go ahead with both things.

**Review by SeverinDK — APPROVED** [review]

**Comment by justbill2020** [comment]
OK, this is now merged. @SeverinDK will you have to tag it as a release and publish to NPM?

Also, my permissions don't allow me to rename the branch.

**Pull request merged**
